dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - flake8
  - pytest  --cov-report term --cov=pytask

after_success:
  - codecov
